### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode characters

### ISSUE THREAD

**Issue by BlayzerQ** [4ndv/lolbot#2]
На сообщения в вк на русском языке сыпит ошибками и вырубается
Traceback (most recent call last):
  File "lolbot.py", line 85, in <module>
    main()
  File "lolbot.py", line 65, in main
    print('> ' + item['body'])
UnicodeEncodeError: 'ascii' codec can't encode characters in position 2-7: ordinal not in range(128)

**Comment by 4ndv** [comment]
Приложите ОС и версию питона

**Comment by BlayzerQ** [comment]
Debian 7 (x64) Wheezy.
Python 3.4

**Comment by BlayzerQ** [comment]
2.7.3 то есть. Перепутал.

**Comment by BlayzerQ** [comment]
Могу даже данные к виртуалке дать, чтобы если что все нужные моменты посмотреть можно было.

**Comment by 4ndv** [comment]
Можно просто закомментировать эту строку

**Comment by BlayzerQ** [comment]
Какую именно? Просто он на любой русский вывод ему в вк крашится. Если закоментировать, как это повлияет на его работу?

**Comment by 4ndv** [comment]
Эту:
![image](https://cloud.githubusercontent.com/assets/10115449/16008319/9cecc1b8-31a1-11e6-9de7-762c6f25e975.png)

На работу повлиять должно абсолютно никак

**Comment by BlayzerQ** [comment]
Попробую.

**Comment by BlayzerQ** [comment]
Да, теперь проблемы нет. А можно как-то все-же изменить, чтобы и запросы парсились (Не коментить данную строку) и чтобы не крашило?

**Comment by palyzx** [comment]
Ошибка у меня такая выпала, когда я запускал бота в OpenWRT. Есть одна переменная окружения, которую питон смотрит - "export PYTHONIOENCODING=UTF-8" . Вот, после этого проблем с падением после print'a русских сивмолов не было. Ну и конечно консоль тогда на utf-8 надо настроить.

P.S. А ещё я во всех print'ах ставил u' ', иначе в винде крякозябры были. Но что-то вижу что не акоммитил это сюда.

**Comment by BlayzerQ** [comment]
А что если добавить туда u?
print(u'> ' + item['body'])

**Comment by BlayzerQ** [comment]
Или это все обернуть наверное надо?
print(u''> ' + item['body']')

**Comment by 4ndv** [comment]
> Или это все обернуть наверное надо?

Нет, так точно делать не надо

**Comment by palyzx** [comment]
> А что если добавить туда u?

Я имел ввиду те места, где есть строковые константы `'блаблабла'`. С переменными же нужно использовать методы `.encode()` `.decode()`. Но думаю в вашем случае всё равно не поможет, т.к. python не знает как вывести русские символы. Сделайте `export PYTHONIOENCODING=UTF-8` (или соотвественно синтаксису вашего шелла) перед запуском `python lolbot.py`. 

Это всё можно прописать в shell скрипт. Я же у себя ещё добавил перезапуск если бот крэшнулся.

**Comment by BlayzerQ** [comment]
А можно код, для перезапуска бота при краше?

**Comment by 4ndv** [comment]
Во всех строковых константах я сам дописывал u, емнип

**Comment by palyzx** [comment]
@BlayzerQ 

Вот код https://bitbucket.org/omv_rtck/python-social-network-bot/src/d392002229bac4a8695ef92d82cd633cf3dc79e9/loader.sh?fileviewer=file-view-default
(в очень черновом репозитории)

@4ndv
Я про вот эти 
`print('Авторизация в вк...')`

В винде крякозябры если запустить. 
я менял на 
`print(u'Авторизация в вк...')`

**Comment by BlayzerQ** [comment]
Я пробовал подобный скрипт,
./start.sh: line 4: syntax error near unexpected token `done'
./start.sh: line 4:`done'

**Comment by BlayzerQ** [comment]
Достаточно дописать в конце ".encode('utf-8')"
А вообще, лучше под if words[0].lower() in prefixes: переносить, чтобы только на команды с префиксом реагировало.
