### ISSUE TITLE
Не отвечает на команды

### ISSUE THREAD

**Issue by BlayzerQ** [4ndv/lolbot#3]
При написании в вк команд, бот их читает, но ничего не отвечает:
Приступаю к приему сообщений

> lb
> boobs
> booobs
> boobs
> lolbot
> boobs

**Comment by BlayzerQ** [comment]
на lolbot boobs откликнулся, а на lb boobs нет.

**Comment by palyzx** [comment]
`prefixes = ['lolbot', u'лолбот', u'лб', u'чб', u'кб']`

Я тут не вижу lb, может `лб boobs` попробуете? Или добавить в префиксы lb.

**Comment by BlayzerQ** [comment]
Да я потом увидел что там лб нет, добавил уже.
Все работает.
