### ISSUE TITLE
Крашится после выполнения скрипта music

### ISSUE THREAD

**Issue by BlayzerQ** [4ndv/lolbot#4]
Отвечает на запрос и крашится.
Приступаю к приему сообщений

> lolbot music
> Traceback (most recent call last):
>   File "lolbot.py", line 85, in <module>
>     main()
>   File "lolbot.py", line 66, in main
>     command(item, cmds)
>   File "lolbot.py", line 81, in command
>     cmds[words[1].lower()].call(message)
>   File "plugins/music.py", line 41, in call
>     for attach in music['items']:
> TypeError: 'NoneType' object has no attribute '**getitem**'

**Comment by palyzx** [comment]
Почему-то при вызове метода audio.getRecommendations он не вернул список. Может нечего возвращать? Нужно проверку дополнительную тогда ставить. А у вас аудиозаписи есть на том аккаунте, с которого ему команду даёте?

**Comment by BlayzerQ** [comment]
Да, он скидывает аудиозаписи даже, затем крашится.

**Comment by BlayzerQ** [comment]
А сейчас выпал просто ответ, без отправки музыки.

Traceback (most recent call last):
  File "lolbot.py", line 85, in <module>
    main()
  File "lolbot.py", line 66, in main
    command(item, cmds)
  File "lolbot.py", line 81, in command
    cmds[words[1].lower()].call(message)
  File "plugins/music.py", line 41, in call
    for attach in music['items']:
TypeError: 'NoneType' object has no attribute '**getitem**'
root@oleg-doktor:/home/VKLOLBot#

**Comment by palyzx** [comment]
>  File "plugins/music.py", line 41, in call
> for attach in music['items']:
> TypeError: 'NoneType' object has no attribute 'getitem'

Вот то место, и та ошибка. На 41 строке он только готовит список. А отвечает намного ниже. 

Тогда интересно увидеть трейсбек того момента, когда уже ответ сделал и свалился.

**Comment by BlayzerQ** [comment]
Выпадает только эта ошибка.
Возможно он пытается подготовить список, но не получается.

**Comment by 4ndv** [comment]
Скорее всего, что-то просто изменилось в API с тех времен, когда был написан бот. Я сейчас на работе, если смогу - то посмотрю вечером из дома.

**Comment by BlayzerQ** [comment]
https://github.com/BlayzerQ/lolbot/blob/master/plugins/music.py
Исправленная версия.

**Comment by 4ndv** [comment]
Буду рад, если оформите в виде пулл-реквеста

**Comment by BlayzerQ** [comment]
Я не умею их делать, на гитхабе недавно. Попробую вечером.
