### ISSUE TITLE
Connection aborted

### ISSUE THREAD

**Issue by BlayzerQ** [4ndv/lolbot#5]
Спустя некоторое время бота критует и он выключается

Traceback (most recent call last):
  File "lolbot.py", line 85, in <module>
    main()
  File "lolbot.py", line 60, in main
    response = vk.api.method('messages.get', values)
  File "/usr/local/lib/python2.7/dist-packages/vk_api/vk_api.py", line 392, in method
    response = self.http.post(url, values)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 518, in post
    return self.request('POST', url, data=data, json=json, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, *_send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 453, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', error("(104, 'ECONNRESET')",))

**Comment by 4ndv** [comment]
Проблема тут не совсем в боте, но в try-catch завернуть надо, это да

**Comment by palyzx** [comment]
Я в своей поделке на основе этого бота сделал пока-что такой "костыль":
https://gist.github.com/palyzx/5968fd636de8a82055ee5e48252e8120

**Comment by BlayzerQ** [comment]
Спасибо.
Вбил в lolbot.py, только что бот так-же упал, код не помог.
Скорее всего я его не в то место вставляю. Но если вставлять в main(), то жалуется на сам код.

**Comment by BlayzerQ** [comment]
https://gist.github.com/BlayzerQ/0b68137203abebbdf6e7d17526990ac2

**Comment by palyzx** [comment]
> Вбил в lolbot.py, только что бот так-же упал, код не помог.

И не поможет. Его нужно изменять и ставить где-то в VkPlus.py . Там же придёться городить прослойку для вызова api.method, а везде где идут вызовы, переделывать их на "прослойку". Ну или как-то красивее сделать. 

P.S. Если вам так интересен бот и собираетесь его доделывать - пишите в личку.

**Comment by BlayzerQ** [comment]
Он мне интересен, но что либо делать на питоне, я могу на уровне интуиции, так как с ним почти не знаком. Повод конечно познакомится получше - данный бот. Мелкие плагины для него начал делать, и хотелось бы просто наладить его работу, чтобы он работал стабильно. Для себя буквально и маленькой конфы в вк.
Я не смог найти где тут личка Оо

**Comment by palyzx** [comment]
Гляньте мой профиль ещё раз. Я тут тоже новичок, по этому не знал где точно разрешить отображение e-mail.

**Comment by 4ndv** [comment]
Можно просто обернуть код с 48 по 70 строки в try-except и не лезть в дебри библиотеки
