### ISSUE TITLE
Запили команду "инфа" и "кто тут"?

### ISSUE THREAD

**Issue by ozu-kun** [4ndv/lolbot#6]
Сделай, пожалуйста, такие команды.

**Comment by 4ndv** [comment]
Увы, но занятость не позволяет сейчас заниматься этим проектом. Свои команды пилить не трудно, достаточно немного посмотреть на плагины и одной поллитры

**Comment by ozu-kun** [comment]
Да, я у меня получилось сделать одну из команд. Но я никак не могу сделать обращение к пользователю, отправившему сообщение боту. Поможете?
